spring:
  application:
    name: aiengine
  config:
    import: "optional:file:/app/config/aiengine-secrets.yml"
server:
  port: 9102

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/

logging:
  file:
    name:  # Leave blank so logs go to stdout
  level:
    root: INFO
    za.co.kpolit.aiengine: DEBUG
  pattern:
    console: '{"aiengine - timestamp": "%d{yyyy-MM-dd HH:mm:ss}", "level": "%-5level", "logger": "%logger{36}", "message": "%msg"}%n'
