spring:
  application:
    name: aiengine
  config:
    import: "optional:file:/app/config/application-secrets.yml"
server:
  port: 9102
  servlet:
    context-path: /aiengine

logging:
  file:
    name:  # Leave blank so logs go to stdout
  level:
    root: INFO
    za.co.kpolit.aiengine: DEBUG
  pattern:
    console: '{"timestamp": "%d{yyyy-MM-dd HH:mm:ss}", "level": "%-5level", "logger": "%logger{36}", "message": "%msg"}%n'
